#!/usr/bin/env python3
"""
Generate a TFT_eSPI / Adafruit-GFX compatible font header from a TTF file.
Covers full Latin-1 range (0x20-0xFF) so German umlauts and ß render correctly.
Usage: python3 gen_gfx_font.py <ttf_path> <size_px> <font_name> <output.h>
"""

import sys
from PIL import Image, ImageDraw, ImageFont

def gen_font(ttf_path, size_px, font_name, output_path):
    font = ImageFont.truetype(ttf_path, size_px)
    ascent, descent = font.getmetrics()
    yAdvance = ascent + descent  # total line height

    FIRST = 0x20
    LAST  = 0xFF

    # Characters we render for real; all others get a zero-width blank glyph.
    REAL_CHARS = set(range(0x20, 0x7F))  # ASCII printable
    REAL_CHARS |= {0xC4, 0xD6, 0xDC, 0xDF, 0xE4, 0xF6, 0xFC}  # German specials

    bitmap_bytes = bytearray()
    glyphs = []  # (bitmapOffset, width, height, xAdvance, xOffset, yOffset)

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        offset = len(bitmap_bytes)

        if code not in REAL_CHARS:
            glyphs.append((offset, 0, 0, 0, 0, 0))
            continue

        # Space and other zero-width chars
        try:
            adv = int(font.getlength(ch) + 0.5)
        except Exception:
            adv = size_px // 3

        try:
            bbox = font.getbbox(ch)
        except Exception:
            glyphs.append((offset, 0, 0, adv, 0, 0))
            continue

        if bbox is None:
            glyphs.append((offset, 0, 0, adv, 0, 0))
            continue

        left, top, right, bottom = bbox
        w = right - left
        h = bottom - top

        if w <= 0 or h <= 0:
            glyphs.append((offset, 0, 0, adv, 0, 0))
            continue

        # Render glyph to a grayscale image
        img = Image.new('L', (w + 2, h + 2), 0)
        draw = ImageDraw.Draw(img)
        draw.text((1 - left, 1 - top), ch, font=font, fill=255)

        # Pack pixels as continuous bit stream (MSB first), no row padding
        byte_val = 0
        bit_pos  = 7
        for row in range(h):
            for col in range(w):
                px = img.getpixel((col + 1, row + 1))
                if px >= 80:  # threshold anti-aliased pixels
                    byte_val |= (1 << bit_pos)
                bit_pos -= 1
                if bit_pos < 0:
                    bitmap_bytes.append(byte_val)
                    byte_val = 0
                    bit_pos  = 7
        if bit_pos != 7:
            bitmap_bytes.append(byte_val)

        x_offset = left
        y_offset = top - ascent  # negative = above baseline
        glyphs.append((offset, w, h, adv, x_offset, y_offset))

    # --- Write header ---
    lines = []
    lines.append(f"// Generated by scripts/gen_gfx_font.py — do not edit")
    lines.append(f"// Font: {ttf_path.split('/')[-1]}, size={size_px}px")
    lines.append(f"#pragma once")
    lines.append(f"#include <pgmspace.h>")
    lines.append(f"#include <gfxfont.h>")
    lines.append(f"")

    # Bitmap array
    lines.append(f"static const uint8_t {font_name}Bitmaps[] PROGMEM = {{")
    row_parts = []
    for i, b in enumerate(bitmap_bytes):
        row_parts.append(f"0x{b:02X}")
        if len(row_parts) == 16 or i == len(bitmap_bytes) - 1:
            lines.append("  " + ", ".join(row_parts) + ",")
            row_parts = []
    lines.append(f"}};")
    lines.append(f"")

    # Glyph table
    lines.append(f"static const GFXglyph {font_name}Glyphs[] PROGMEM = {{")
    lines.append(f"  // bitmapOffset, width, height, xAdvance, xOffset, yOffset")
    for code, (off, w, h, adv, xo, yo) in enumerate(glyphs, FIRST):
        ch_comment = chr(code) if 0x20 <= code <= 0x7E else f"U+{code:04X}"
        lines.append(f"  {{ {off:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:3d}, {yo:4d} }},  // '{ch_comment}'")
    lines.append(f"}};")
    lines.append(f"")

    # Font struct
    lines.append(f"static const GFXfont {font_name} PROGMEM = {{")
    lines.append(f"  (uint8_t  *){font_name}Bitmaps,")
    lines.append(f"  (GFXglyph *){font_name}Glyphs,")
    lines.append(f"  0x{FIRST:02X}, 0x{LAST:02X},")
    lines.append(f"  {yAdvance}  // yAdvance")
    lines.append(f"}};")

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Written {len(glyphs)} glyphs, {len(bitmap_bytes)} bitmap bytes → {output_path}")

if __name__ == '__main__':
    if len(sys.argv) != 5:
        print("Usage: gen_gfx_font.py <ttf> <size> <name> <output.h>")
        sys.exit(1)
    gen_font(sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4])
